config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  post 'question/create' => 'question#create'
  get 'question/create'
  get 'question/list' => 'question#list'
  get 'question/semnet' => 'question#semnet'
  get 'question/semnet2' => 'question#semnet2'
  #get 'question/demo' => 'question#demo'
  match 'question/demo', as: 'demo', to: 'question#demo', via: [:get, :post]

  get 'drill/drill' => 'drill#drill'
  match 'drill/drill', as: 'drill', to: 'drill#drill', via: [:get, :post]

  root 'home#top'
  get '/show'  => 'home#show'
  get '/about' => 'home#about'
  #get '/gaze'  => 'home#gaze'
  match '/gaze', as: 'gaze', to: 'home#gaze', via: [:get, :post]
  #get '/video' => 'home#video'

end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_action :authenticate_user!, only: :list

  def create
    con = ActiveRecord::Base.connection
    nm = Natto::MeCab.new(userdic: "/home/vagrant/aquarium/dic/alkali.dic")

    @problem = params[:problem]
    word = Array.new
    unless @problem.blank? then
      nm.parse(@problem) do |w|
        if w.feature.split(',')[0] == '名詞' || w.feature.split(',')[0] == '動詞' then
          word.push(w.surface)
        end
      end
    end

    @e = word[0]
    @a = word[1]
    @v = params[:right]
    @w1 = params[:wrong1]
    @w2 = params[:wrong2]
    @w3 = params[:wrong3]

    @check = true
    if con.select_all("select val from alkalis where ent like '#{@e}' and att like '#{@a}' and val like '%'").to_a.empty? then
      @check = false
    end

    @res1 = con.select_all("select val from alkalis where ent like '#{@e}' and att like '#{@a}' and val like '#{@v}'")
    @res2 = con.select_all("select val from alkalis where ent like '#{@e}' and att like '#{@a}' and val like '#{@w1}'")
    @res3 = con.select_all("select val from alkalis where ent like '#{@e}' and att like '#{@a}' and val like '#{@w2}'")
    @res4 = con.select_all("select val from alkalis where ent like '#{@e}' and att like '#{@a}' and val like '#{@w3}'")

    @flag = true;
   if @check then
      if @res1.count == 0 then
        @flag = false
        @ret1 = con.select_all("select val from alkalis where ent like '#{@e}' AND att like '#{@a}' AND val like '%'")[0].to_h.fetch("val")
      end
      if @res2.count >= 1 then
        @flag = false
        @ret2 = con.select_all("select val from alkalis where ent like '#{@e}' AND att like '#{@a}' AND val like '#{@w1}'")[0].to_h.fetch("val")
      end
      if @res3.count >= 1 then
        @flag = false
        @ret3 = con.select_all("select val from alkalis where ent like '#{@e}' AND att like '#{@a}' AND val like '#{@w2}'")[0].to_h.fetch("val")
      end
      if @res4.count >= 1 then
        @flag = false
        @ret4 = con.select_all("select val from alkalis where ent like '#{@e}' AND att like '#{@a}' AND val like '#{@w3}'")[0].to_h.fetch("val")
      end
   end

   @ok = false
   if @check && @flag then @ok = true end
  end

  def list
    @role  = current_user.role.to_i
    @user  = current_user.username.to_s
    @user_id = current_user.id
    if @role == 0 then
      @data = QuestionAlkali.where(author_id: @user_id)
    elsif @role == 1 then
      @data = QuestionAlkali.all
    end
    @state = {0 => "不明", 1 => "既知", 2 => "誤り", 3 => "定着"}
    @color = {0 => "warning", 1 => "info", 2 => "danger", 3 => "success"}
  end

  def semnet
    node = Array.new
    triad = Hash.new { |h,k| h[k] = {} } # 2次元ハッシュの初期化
    state = Hash.new { |h,k| h[k] = {} } # 2次元ハッシュの初期化
    color = {0 => "#FCF8E3", 1 => "#D9EDF7", 2 => "#F2DEDE", 3 => "#DFF0D8"}
    #color = {0 => "gold", 1 => "lightskyblue", 2 => "pink", 3 => "green"}
    role  = current_user.role.to_i
    user  = current_user.username.to_s.capitalize
    if role == 0 then
      #data = "#{user}Alkali".constantize.all
      #data = Test1Alkali.all
      data = "#{user}Periodictable".constantize.all
      data.each do |datum|
        #if datum.state == 0 then
        node.push(datum.ent)
        node.push(datum.val)
        #end
        triad[datum.ent][datum.val] = datum.att
        state[datum.ent][datum.val] = color[datum.state]
      end
      gon.triad = triad
      gon.state = state
      gon.role  = role
      gon.node  = node.uniq!
    end
  end

  def demo
    con = ActiveRecord::Base.connection
    nm = Natto::MeCab.new(userdic: "/home/vagrant/aquarium/dic/alkali.dic")
    #nm = Natto::MeCab.new(userdic: "/home/vagrant/aquarium/dic/ohenro.dic")
    @prob = false
    @tern2 = false
    @finish = false
    @role  = current_user.role.to_i
    @user_id = current_user.id
    @user  = current_user.username.to_s
    @transition = false # 作問フェーズからの離脱
    # 推定機能
    @is_conf_e = false
    @is_conf_a = false
    @is_conf_r = false
    @conf_e = Array.new()
    @conf_a = Array.new()
    @conf_r = Array.new()
    # 誘導作問
    nodes = Array.new()
    @all_nodes = Hash.new(0) # 全ノード
    @ack_nodes = Hash.new(0) # 既知ノード
    #@intelli = Hash.new{ |h,k| h[k] = {} } # 単語、母数、理解度の三組
    @intelli = Hash.new(0)
    @remain = Hash.new(0)

    if @role == 0 then
      @data  = "#{@user.capitalize}Alkali".constantize.all
      #@data  = "#{@user.capitalize}Ohenro".constantize.all
    end
    @state = {0 => "不明", 1 => "既知", 2 => "誤り", 3 => "定着"}
    @color = {0 => "warning", 1 => "info", 2 => "danger", 3 => "success"}

    node = Array.new
    triad = Hash.new { |h,k| h[k] = {} } # 2次元ハッシュの初期化
    state = Hash.new { |h,k| h[k] = {} } # 2次元ハッシュの初期化
    color = {0 => "#FCF8E3", 1 => "#D9EDF7", 2 => "#F2DEDE", 3 => "#DFF0D8"}
    @data.each do |datum|
      #if datum.state == 0 then
        node.push(datum.ent)
        node.push(datum.val)
      #end
      triad[datum.ent][datum.val] = datum.att
      state[datum.ent][datum.val] = color[datum.state]
    end
    gon.triad = triad
    gon.state = state
    gon.node = node.uniq!
    gon.cnt = 0

    # 形態素解析
    word = Array.new
    if params['ajx'].present?
      $txt = params['ajx']['problem']

      # 作問できない場合
      if $txt.include?("作問できません")
        @transition = true

        kw = KeywordPeriodictable.all
        model = Test1Periodictable.all

        kw_arr = []
        kw_cnt = Hash.new(0)

        kw.order(:keyword).each do |w|
          if w.watch # watchがtrueならば
            model.each do |i|
              if i.state == 0
                k = w.keyword
                if (i.ent == k) || (i.att == k) || (i.val == k)
                  kw_arr << k
                end
              end
            end
          end
        end

        kw_arr.each do |e|
          kw_cnt[e] += 1
        end
        @target = kw_cnt.sort_by {|_,v| -v}[0][0]

      end

      # XのYは何ですか？
      nm.parse($txt) do |w|
        word.push(w.surface)
        if w.surface == 'の' then
          word.pop
          $e = word.join
          word.clear
        end
        if w.surface == 'は' then
          word.pop
          $a = word.join
          word.clear
        end
        #if w.feature.split(',')[0] == '名詞' || w.feature.split(',')[0] == '動詞' then
          #word.push(w.surface)
        #end
      end
      p word
      #$e = word[0]
      #$a = word[1]
      unless con.select_all("select val from alkalis where ent like '#{$e}' and att like '#{$a}' and val like '%'").to_a.empty? then
      #unless con.select_all("select val from ohenros where ent like '#{$e}' and att like '#{$a}' and val like '%'").to_a.empty? then
        @prob = true
      end
    end

    # 別名定義
    @has_alias = false # 別名定義が存在するかのフラグ
      terms1 = con.select_all("select ent from alkalis where ent like '%' and att like '名称' and val like '#{$e}'").to_a
      #terms1 = con.select_all("select ent from ohenros where ent like '%' and att like '別名' and val like '#{$e}'").to_a
      terms2 = con.select_all("select val from alkalis where ent like '#{$e}' and att like '名称' and val like '%'").to_a
      #terms2 = con.select_all("select val from ohenros where ent like '#{$e}' and att like '別名' and val like '%'").to_a
    if !terms1.empty? && terms2.empty? then
      @alias_def = terms1[0].fetch("ent")
      @has_alias = true
    end

    # 別名定義(正答)
    @has_alias_r = false # 別名定義が存在するかのフラグ
      terms1 = con.select_all("select ent from alkalis where ent like '%' and att like '別名' and val like '#{$right}'").to_a
      #terms1 = con.select_all("select ent from ohenros where ent like '%' and att like '別名' and val like '#{$right}'").to_a
      terms2 = con.select_all("select val from alkalis where ent like '#{$right}' and att like '別名' and val like '%'").to_a
      #terms2 = con.select_all("select val from ohenros where ent like '#{$right}' and att like '別名' and val like '%'").to_a
    if !terms1.empty? && terms2.empty? then
      @alias_def_r = terms1[0].fetch("ent")
      #@conf_r.push(@alias_def_r)
      @has_alias_r = true
    end

    ### 誘導作問
    # 配列にノードとなり得る値を追加
    @data.each do |datum|
      nodes.push(datum.ent)
      nodes.push(datum.val)
    end

    nodes.each do |elem|
      @all_nodes[elem] += 1 # 全ノード数のカウント
      @ack_nodes[elem] = 0  # 既知ノード数の初期化
    end
    # 隣接既知ノード数の計算
    nodes.uniq!.each do |elem|
      @data.each do |datum|
        if datum.ent == elem || datum.val == elem then
          if datum.state == 1
            @ack_nodes[elem] += 1
          end
        end
      end
    end
    # 理解度の計算
    nodes.each do |elem|
      if @all_nodes[elem] > 1
        @intelli[elem] = @ack_nodes[elem] / @all_nodes[elem].to_f
        @remain[elem] = @all_nodes[elem] - @ack_nodes[elem]
      end
    end
    p "理解度昇順ソート"
    p @intelli.sort {|a,b| b[1] <=> a[1]}.reverse!
    p "残数降順ソート"
    p @remain.sort {|a,b| a[1] <=> b[1]}.reverse!


    # ドリル＆プラクティス
    @choices = Array.new()
    @data.each do |datum|
      if datum.att == "炎色反応" then
        @choices.push(datum.val)
      end
    end

    # パスをするが押されたかどうかの判定
    @is_pass = false
    if params['pass']
      @is_pass = true
    end

    # 該当なしボタンが押されたかどうかの判定
    @nohit = false
    if params['nohit']
      @nohit = true
    end

    @nohit_r = false
    if params['nohit_r']
      @nohit_r = true
    end

    # 問題文入力後、ボタンが押されたかどうかの判定
    @problem = false
    if params['problem']
      @problem = true
    end

    # 正答誤答入力後、ボタンが押されたかどうかの判定
    @create = false
    if params['create']
      @create = true
      @tern2 = true
    end

    # 元の文章を用いて問題文を修正するかどうかの判定
    @is_fix = 2
    if params['fix_yes']
      @is_fix = 1
    elsif params['fix_no']
      @is_fix = 0
    end

    # 新しく問題を作り直すかどうかの判定
    @is_new = 2
    if params['new_yes']
      @is_new = 1
    elsif params['new_no']
      @is_new = 0
    end

    # 作問を続けるかどうかの判定
    @is_continue = 2
    if params['continue_yes']
      @is_continue = 1
    elsif params['continue_no']
      @is_continue = 0
    end

    # 知識状態のリセット

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/question/create.html.erb
<h2>問題作成</h2>
<hr>
<% if @ok %>
  <div class="alert alert-success" role="alert"><strong>success</strong>：　良い問題ですね。</div>
<% end %>

<%= form_tag question_create_path do %>
  <% if !@problem.blank? && !@check %>
    <div class="alert alert-danger" role="alert"><strong>danger</strong>：　問題文が間違っています。</div>
  <% end %>
  <h5>問題文</h5>
  <div class="mdl-textfield mdl-js-textfield" style="width:350px">
    <input class="mdl-textfield__input" type="text" id="problem" name="problem" <% if !@ok %> value="<%= @problem %>" <% end %> required>
    <label class="mdl-textfield__label" for="problem">問題文を入力してください（例:XのYは何ですか？）</label>
  </div>
  <% if !@problem.blank? && @res1.count == 0 && @check %>
    <div class="alert alert-danger" role="alert"><strong>danger</strong>：　正答が間違っています。</div>
    <div class="alert alert-warning" role="alert"><strong>warning</strong>：　正しくは <%= @e %> の <%= @a %> は <%= @ret1 %> です。</div>
  <% end %>
  <h5>正答</h5>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="right" name="right" <% if !@ok %> value="<%= @v %>" <% end %> required>
    <label class="mdl-textfield__label" for="right">正答</label>
  </div>
  <% if !@problem.blank? && @res2.count >= 1 %>
    <div class="alert alert-danger" role="alert"><strong>danger</strong>：　誤答1が間違っています。</div>
    <div class="alert alert-warning" role="alert"><strong>warning</strong>：　「<%= @e %> の <%= @a %> は <%= @ret2 %> 」は正しいです。</div>
  <% end %>
  <h5>誤答1</h5>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong1" name="wrong1" <% if !@ok %> value="<%= @w1 %>" <% end %> required>
    <label class="mdl-textfield__label" for="wrong1">誤答1</label>
  </div>
  <% if !@problem.blank? && @res3.count >= 1 %>
    <div class="alert alert-danger" role="alert"><strong>danger</strong>：　誤答2が間違っています。</div>
    <div class="alert alert-warning" role="alert"><strong>warning</strong>：　「<%= @e %> の <%= @a %> は <%= @ret3 %> 」は正しいです。</div>
  <% end %>
  <h5>誤答2</h5>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong2" name="wrong2" <% if !@ok %> value="<%= @w2 %>" <% end %> required>
    <label class="mdl-textfield__label" for="wrong2">誤答2</label>
  </div>
  <% if !@problem.blank? && @res4.count >= 1 %>
    <div class="alert alert-danger" role="alert"><strong>danger</strong>：　誤答3が間違っています。</div>
    <div class="alert alert-warning" role="alert"><strong>warning</strong>：　「<%= @e %> の <%= @a %> は <%= @ret4 %> 」は正しいです。</div>
  <% end %>
  <h5>誤答3</h5>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong3" name="wrong3" <% if !@ok %> value="<%= @w3 %>" <% end %> required>
    <label class="mdl-textfield__label" for="wrong3">誤答3</label>
  </div>
  <br>
  <input type="submit" value="作成" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
<% end %>

app/views/question/demo.html.erb
<ul class="nav nav-tabs">
  <li><a href="#create" data-toggle="tab">作問画面</a></li>
  <li><a href="#inner" data-toggle="tab">内部処理</a></li>
  <li><a href="#knowledge" data-toggle="tab">知識状態</a></li>
</ul>

<p id="page-top"><a href="#top"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></p>

<div class="tab-content">
  <div class="tab-pane fade in active" id="create">
    <br><br>
    <div id="dialogue">
    <div class="well">
      <%= image_tag 'pc.png', :size => '40x32', :align => 'middle' %> &nbsp;&nbsp;
      <font size="3">問題文を入力してください。</font>
    </div>
    <%= form_for('demo', :method => :post, :remote => true, :id => "ajx", html: {'name' => 'demo' ,'data-parsley-validate' => '', 'parsley-use-html5-constraints' => false, :autocomplete => :off}) do %>
      <div class="well">
        <div class="form-inline form-group">
          <div class="form-group">
            <%= image_tag 'person.png', :size => '40x40', :align => 'middle' %> &nbsp;&nbsp;
            <%= text_field_tag('ajx[problem]', nil, size: '60', class: 'form-control', placeholder: '例） X の Y は何ですか？') %>
          </div>
          <div class="form-group">
            <%= button_tag(type: "submit", class: "btn btn-primary", id: "problem", name: "problem") do %>
              <i class="fa fa-paper-plane-o" aria-hidden="true"></i> 作成
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
    <div id="finish"></div>
  </div>
  <div class="tab-pane fade" id="inner">
    <br><br>
    <pre class="console">
      <div id="console"></div>
      <div id="ld_e"></div>
      <div id="ld_a"></div>
    </pre>
  </div>
  <div class="tab-pane fade" id="knowledge">
    <br><br>
    <button type="submit", class="btn btn-primary", onclick="toggle(1)"> 表形式 </button>
    <button type="submit", class="btn btn-primary", onclick="toggle(2)"> 意味ネットワーク </button>
    <div align="right">
      <%= form_for("demo", :method => :post, :remote => true, :id => "reset", :data => { :confirm => '本当にリセットしますか？'}) do %><%= button_tag(type: "submit", class: "btn btn-danger", name: "reset", id: "reset") do %> リセット <% end %><% end %>
    </div>
    <br><br>
    <script>
function toggle(id) {
  if ( id == 1 ) {
    $("#knowledge-table").html("<table id='knowledge-state' border='1' class='table table-hover'><thead><tr><th>entity</th><th>attribute</th><th>value</th><th>知識状態</th></tr></thead><tbody><% @data.reload.each do |datum| %><tr class=<%= @color[datum.state] %>><td><%= datum.ent %></td><td><%= datum.att %></td><td><%= datum.val %></td><td><%= @state[datum.state] %></td></tr><% end %></tbody></table><script>\$(document).ready(function(){\$('#knowledge-state').DataTable({'paging':true,'bProcessing':true,'iDisplayLength':10});});<\/script>");
    $("#semnet").html("");
} else if ( id == 2 ) {
    $("#knowledge-table").html("");
    $("#semnet").html("<script>var nodes = [];for ( var i in gon.node ) {nodes.push({id: (gon.node[i]), label: (gon.node[i])});}var edges = [];for (var ent in gon.triad) {for ( var val in gon.triad[ent] ) {edges.push({from: ent, to: val, label: gon.triad[ent][val]});}}var container = document.getElementById('semnet');var data = {nodes: nodes,edges: edges};var options = {nodes: { shape: 'box', font: { size: 25} },edges: { arrows: 'to', font: { size: 16, align: 'top' } }};var network = new vis.Network(container, data, options);<\/script>");
  }
}
    </script>
    <div id="knowledge-table"></div>
    <div id="semnet" class="center-block"></div>
  </div>
</div>

app/views/question/demo2.html.erb
<div class="container">
  <div class="row">
    <div id="hoge" class="col-sm-12">
      <h3>問題入力過程</h3>
      <section>
        <%= form_for('demo', :method => :post, :remote => true, :id => "ajx", html: {'data-parsley-validate' => '', 'parsley-use-html5-constraints' => false}) do %>
          <div class="field">
            <h4>問題文を入力してください</h4>
            <div class="col-xs-6">
              <%= text_field_tag('ajx[answer]', nil, class: 'form-control', placeholder: '例） X の Y は何ですか？', 'required' => '') %>
            </div>
            <%= button_tag(type: "submit", class: "btn btn-primary") do %> 作成 <% end %>
          </div>
        <% end %>
      </section>
      <h3>推定過程</h3>
      <section>
        <div id="sec"></div>
      </section>
      <h3>正誤判定</h3>
      <section>
        <%= form_for('demo', :method => :post, :remote => true, :id => "ajx", html: {'data-parsley-validate' => '', 'parsley-use-html5-constraints' => false}) do %>
          <div class="field">
            <h4>正答と誤答3つを入力してください。</h4>
            <div class="col-xs-3">
              <%= text_field_tag('ajx[answer]', nil, class: 'form-control', placeholder: '正答', 'required' => '') %>
            </div>
            <div class="col-xs-3">
              <%= text_field_tag('ajx[answer]', nil, class: 'form-control', placeholder: '誤答1', 'required' => '') %>
            </div>
            <div class="col-xs-3">
              <%= text_field_tag('ajx[answer]', nil, class: 'form-control', placeholder: '誤答2', 'required' => '') %>
            </div>
            <div class="col-xs-3">
              <%= text_field_tag('ajx[answer]', nil, class: 'form-control', placeholder: '誤答3', 'required' => '') %>
            </div><br><br><br>
            <div class="pull-right">
              <%= button_tag(type: "submit", class: "btn btn-primary") do %> 作成 <% end %>
            </div>
          </div>
        <% end %>
      </section>
    </div>
    <script>
    $("#hoge").steps({
      headerTag: "h3",
      bodyTag: "section",
      transitionEffect: "slideLeft",
      autoFocus: true,
      titleTemplate: "#title#",
      labels: {
        next: "次へ",
        previous: "戻る",
        finish: "完了！"
      }
    });
    </script>
  </div>
  <hr><br>
  <div class="row">
    <div class="col-sm-6">
      <pre class="console">
        <div id="txt"></div>
        <div id="entity"></div>
        <div id="attribute"></div>
      </pre>
    </div>
    <div class="col-sm-6">
      <table id='knowledge-state' border='1' class="table table-hover">
        <thead>
          <tr>
            <th>entity</th><th>attribute</th><th>value</th><th>知識状態</th>
          </tr>
        </thead>
        <tbody>
        <% @data.each do |datum| %>
          <tr class=<%= @color[datum.state] %>>
            <td><%= datum.ent %></td>
            <td><%= datum.att %></td>
            <td><%= datum.val %></td>
            <td><%= @state[datum.state] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <script>
      $(document).ready(function(){
        $('#knowledge-state').DataTable({
          "paging": true,
          "bProcessing": true,
          "iDisplayLength": 6
        });
      });
      </script>
    </div>
  </div>
</div>

app/views/question/list.html.erb
<% if @role == 1 %>
  <h3> teacher </h3>
  <div><a class="btn btn-primary" href="/question/semnet">意味ネットワーク</a></div><br>
  <h3>作問知識ベース</h3>
  <table border='1' class="table table-hover">
    <tr>
      <th>問題文</th><th>正答</th><th>誤答1</th><th>誤答2</th><th>誤答3</th><th>作成者id</th><th>作成者名</th>
    </tr>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.question %></td>
        <td><%= datum.correct %></td>
        <td><%= datum.wrong1 %></td>
        <td><%= datum.wrong2 %></td>
        <td><%= datum.wrong3 %></td>
        <td><%= datum.author_id %></td>
        <td><%= datum.author_name %></td>
      </tr>
    <% end %>
  </table>
<% elsif @role == 0 %>
  <h3><%= @user %> さんが作成した問題</h3>
  <table border='1' class="table table-hover">
    <tr>
      <th>問題文</th><th>正答</th><th>誤答1</th><th>誤答2</th><th>誤答3</th>
    </tr>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.question %></td>
        <td><%= datum.correct %></td>
        <td><%= datum.wrong1 %></td>
        <td><%= datum.wrong2 %></td>
        <td><%= datum.wrong3 %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/question/make.html.erb
<%= form_tag do %>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="sentence">
    <label class="mdl-textfield__label" for="sentence">問題文を入力してください（例:XのYは何ですか？）</label>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="right">
    <label class="mdl-textfield__label" for="right">正答</label>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong1">
    <label class="mdl-textfield__label" for="wrong1">誤答1</label>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong2">
    <label class="mdl-textfield__label" for="wrong2">誤答2</label>
  </div>
  <br>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" id="wrong3">
    <label class="mdl-textfield__label" for="wrong3">誤答3</label>
  </div>
  <br>
  <input type="submit" value="作成" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
  <% end %>

app/views/question/semnet.html.erb
<h3>意味ネットワーク</h3>
<!--<div class="row">
  <div class="col-xs-2">
    <select class="form-control">
      <option>アルカリ金属</option>
      <option>計算機入門 I</option>
    </select>
  </div>
  <input class="btn btn-primary" type="button" onclick="location.reload()" value="Reload"> <br /><br />
</div>-->

<div id="semnet"></div>

<script type="text/javascript">
var nodes = [];

// create an array with nodes
for ( var i in gon.node ) {
  nodes.push({id: (gon.node[i]), label: (gon.node[i]), color: {background: ''}});
  //document.write(gon.node[i]+"<br>");
}
  document.write("<br>");
//nodes.push({id: 'hoge', label: 'hoge', hidden: false});
// create an array with edges
var edges = [];
for (var ent in gon.triad) {
  for ( var val in gon.triad[ent] ) {
    edges.push({from: ent, to: val, label: gon.triad[ent][val], font: {color: ''}});
    //document.write(ent+" "+gon.triad[ent][val]+" "+val+" "+gon.state[ent][val]+"<BR>");
  }
}

if ( gon.role == 0 ) {
  for (var ent in gon.triad) {
    for (var val in gon.triad[ent]) {
      if ( gon.state[ent][val] != "#D9EDF7" ) {
        //document.write(ent+" "+gon.triad[ent][val]+" "+val+"<br>");
        for (var i = 0, l = nodes.length; i < l; i++) {
          //if (nodes[j].id == ent) {
          //  nodes[j].color.background = '#343434';
          //}
          if (nodes[i].id == val) {
            nodes[i].color.background = '#343434';
          } else {
            //nodes[i].color.background = gon.state[ent][val];
          }
        }
        for (var i = 0, l = edges.length; i < l; i++) {
          if (edges[i].to == val) {
            edges[i].font.color = 'white'
          }
        }
      }
    }
  }
}
if ( gon.role == 1 ) {
  for (var ent in gon.triad) {
    for (var val in gon.triad[ent]) {
      for (var i = 0, l = nodes.length; i < l; i++) {
        if (nodes[i].id == val) {
          nodes[i].color.background = gon.state[ent][val];
        }
      }
    }
  }
}
//document.write("<br><br>nodes<br>");
//document.write(JSON.stringify(nodes));
//document.write("<br><br>edges<br>");
//document.write(JSON.stringify(edges));

// create a network
var container = document.getElementById('semnet');
var data = {
  nodes: nodes,
  edges: edges
};
var options = {
nodes: { shape: 'box', font: { size: 25} },
edges: { arrows: 'to', font: { size: 16, align: 'top' } }
};
var network = new vis.Network(container, data, options);

</script>